
/**
 * generated by http://RDFReactor.ontoware.org on 10.05.06 00:53
 */
package org.ontoware.rdfreactor.example;

import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.Resource;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.RDFDataException;


/**
 * This class was generated by <a href="http://RDFReactor.ontoware.org">RDFReactor</a> on 10.05.06 00:53
 * This class manages access to these properties:
 * <ul>
 *   <li> Name </li>
 *   <li> PublishedAt </li>
 * </ul>
 */
public class Paper extends Thing {

    /** http://purl.org/net/xamde/ns/test#Paper */
	public static final URI RDFS_CLASS = URIImpl.createURIWithoutChecking("http://purl.org/net/xamde/ns/test#Paper");

    /** http://purl.org/net/xamde/ns/test#hasName */
	public static final URI NAME = URIImpl.createURIWithoutChecking("http://purl.org/net/xamde/ns/test#hasName");

    /** http://purl.org/net/xamde/ns/test#publishedAt */
	public static final URI PUBLISHEDAT = URIImpl.createURIWithoutChecking("http://purl.org/net/xamde/ns/test#publishedAt");
	
	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier URI, BlankNode or URL that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	protected Paper ( Model model, URI classURI, Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uri URI of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Paper ( Model model, Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uri URI of this instance
	 */
	public Paper ( Model model, URI uri ) {
		this(model, uri, true);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString A URI of this instance, represented as a String
	 * @throws ModelRuntimeException 
	 */
	public Paper ( Model model, String uriString ) throws ModelRuntimeException {
		super(model, uriString);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 */
	public Paper ( Model model, BlankNode bnode ) {
		this(model, bnode, true);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 */
	public Paper ( Model model ) {
		this(model, RDFS_CLASS, true);
	}


    ///////////////////////////////////////////////////////////////////
    // getters, setters, ...

	/**
	 * @return all instances of this class
	 */
	public Paper[] getAllInstances() {
		return (Paper[]) getAllInstances(super.model, Paper.class);
	}

	/**
	 * @return all instances of this class in the given Model
	 * @param model an RDF2Go model
	 */
	public static Paper[] getAllInstances(Model model) {
		return (Paper[]) getAllInstances(model, Paper.class);
	}

	/**
	 * @return all A's that have a relation 'Writes' to this Paper instance
	 */
	public Researcher[] getAllWrites_Inverse() {
		return (Researcher[]) getAll_Inverse(Researcher.WRITES, this.getResource(), Researcher.class);
	}

	/**
	 * add 'Writes'-Inverse
	 */
	public void addWrites_Inverse(Researcher value) {
		value.add( Researcher.WRITES ,this);
	}



    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public java.lang.String getName() {
		return (java.lang.String) get(NAME, java.lang.String.class);
	}

	/**
	 * removes all values and sets this one
	 */
	public void setName( java.lang.String value ) {
		set(NAME, value);
	}

 	/**
	 * removes a value
	 */
	public void removeName( java.lang.String value  ) {
		remove(NAME, value);
	}
  
	/**
	 * adds a value
	 */
	public void addName( java.lang.String value  ) {
		add(NAME, value );
	}
 
	/**
	 * returns all values
	 */
	public java.lang.String[] getAllName() {
		return (java.lang.String[]) getAll(NAME, java.lang.String.class);
	}
 

    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Conference getPublishedAt() {
		return (Conference) get(PUBLISHEDAT, Conference.class);
	}

	/**
	 * removes all values and sets this one
	 */
	public void setPublishedAt( Conference value ) {
		set(PUBLISHEDAT, value);
	}

 	/**
	 * removes a value
	 */
	public void removePublishedAt( Conference value  ) {
		remove(PUBLISHEDAT, value);
	}
  
	/**
	 * adds a value
	 */
	public void addPublishedAt( Conference value  ) {
		add(PUBLISHEDAT, value );
	}
 
	/**
	 * returns all values
	 */
	public Conference[] getAllPublishedAt() {
		return (Conference[]) getAll(PUBLISHEDAT, Conference.class);
	}
  }

  
  
