
/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 785 2007-05-31 15:47:01Z voelkel $) on 01.06.07 17:50
 */
package org.ontoware.rdfreactor.schema.owl;

import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.RDFDataException;
import org.ontoware.rdfreactor.schema.rdfschema.Property;


/**
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 01.06.07 17:50
 * This class manages access to these properties:
 * <ul>
 *   <li> OnProperty </li>
 *   <li> MaxCardinality </li>
 *   <li> AllValuesFrom </li>
 *   <li> MinCardinality </li>
 *   <li> SomeValuesFrom </li>
 *   <li> Cardinality </li>
 *   <li> HasValue </li>
 * </ul>
 */
public class Restriction extends Class {

    /** http://www.w3.org/2002/07/owl#Restriction */
	public static final URI RDFS_CLASS = new URIImpl("http://www.w3.org/2002/07/owl#Restriction", false);

    /** http://www.w3.org/2002/07/owl#onProperty */
	public static final URI ONPROPERTY = new URIImpl("http://www.w3.org/2002/07/owl#onProperty",false);

    /** http://www.w3.org/2002/07/owl#maxCardinality */
	public static final URI MAXCARDINALITY = new URIImpl("http://www.w3.org/2002/07/owl#maxCardinality",false);

    /** http://www.w3.org/2002/07/owl#allValuesFrom */
	public static final URI ALLVALUESFROM = new URIImpl("http://www.w3.org/2002/07/owl#allValuesFrom",false);

    /** http://www.w3.org/2002/07/owl#minCardinality */
	public static final URI MINCARDINALITY = new URIImpl("http://www.w3.org/2002/07/owl#minCardinality",false);

    /** http://www.w3.org/2002/07/owl#someValuesFrom */
	public static final URI SOMEVALUESFROM = new URIImpl("http://www.w3.org/2002/07/owl#someValuesFrom",false);

    /** http://www.w3.org/2002/07/owl#cardinality */
	public static final URI CARDINALITY = new URIImpl("http://www.w3.org/2002/07/owl#cardinality",false);

    /** http://www.w3.org/2002/07/owl#hasValue */
	public static final URI HASVALUE = new URIImpl("http://www.w3.org/2002/07/owl#hasValue",false);

    /** all property-URIs with this class as domain */
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://www.w3.org/2002/07/owl#onProperty",false),
      new URIImpl("http://www.w3.org/2002/07/owl#maxCardinality",false),
      new URIImpl("http://www.w3.org/2002/07/owl#allValuesFrom",false),
      new URIImpl("http://www.w3.org/2002/07/owl#minCardinality",false),
      new URIImpl("http://www.w3.org/2002/07/owl#someValuesFrom",false),
      new URIImpl("http://www.w3.org/2002/07/owl#cardinality",false),
      new URIImpl("http://www.w3.org/2002/07/owl#hasValue",false) 
    };

	
	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	protected Restriction ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Restriction ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Restriction ( Model model, String uriString, boolean write) {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Restriction ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Restriction ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // getters, setters, ...

	/**
	 * @param model RDF2Go model
	 * @param uri instance identifier
	 * @return an instance of Restriction or null if none existst
	 * @throws Exception if Model causes problems
	 */
	public static Restriction getInstance(Model model, URI uri) throws Exception {
		return (Restriction) getInstance(model, uri, Restriction.class);
	}

	/**
	 * @param model
	 * @param uri
	 * @return true if uri is an instance of this class in the model
	 */
	public static boolean hasInstance(Model model, URI uri) {
		return hasInstance(model, uri, RDFS_CLASS);
	}

	/**
	 * @return all instances of this class
	 */
	public Restriction[] getAllInstances() {
		return (Restriction[]) getAllInstances(super.model, Restriction.class);
	}

	/**
	 * @return all instances of this class in the given Model
	 * @param model an RDF2Go model
	 */
	public static Restriction[] getAllInstances(Model model) {
		return (Restriction[]) getAllInstances(model, Restriction.class);
	}


    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Property getOnProperty() {
		return (Property) get(ONPROPERTY, Property.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
	 */
	public void setOnProperty( Property value ) {
		set(ONPROPERTY, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
	 */
	public void removeOnProperty( Property value  ) {
		remove(ONPROPERTY, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, ONPROPERTY, value)
	 */
	public boolean hasOnProperty( Property value) {
		return hasValue(ONPROPERTY, value);
	}

	/**
	 * @return true if the model contains a statement (this, ONPROPERTY, *)
	 */
	public boolean hasOnProperty() {
		return hasValue(ONPROPERTY);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
	 */
	public void addOnProperty( Property value  ) {
		add(ONPROPERTY, value );
	}

	/**
	 * @return all values
	 */
	public Property[] getAllOnProperty() {
		return (Property[]) getAll(ONPROPERTY, Property.class);
	}
  

    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public int getMaxCardinality() {
		return (Integer) get(MAXCARDINALITY, Integer.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
	 */
	public void setMaxCardinality( int value ) {
		set(MAXCARDINALITY, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
	 */
	public void removeMaxCardinality( int value  ) {
		remove(MAXCARDINALITY, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, MAXCARDINALITY, value)
	 */
	public boolean hasMaxCardinality( int value) {
		return hasValue(MAXCARDINALITY, value);
	}

	/**
	 * @return true if the model contains a statement (this, MAXCARDINALITY, *)
	 */
	public boolean hasMaxCardinality() {
		return hasValue(MAXCARDINALITY);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
	 */
	public void addMaxCardinality( int value  ) {
		add(MAXCARDINALITY, value );
	}

	/**
	 * @return all values
	 */
	public int[] getAllMaxCardinality() {
		return toIntArray((Integer[]) getAll(MAXCARDINALITY, Integer.class) );
	}
  

    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Class getAllValuesFrom() {
		return (Class) get(ALLVALUESFROM, Class.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
	 */
	public void setAllValuesFrom( Class value ) {
		set(ALLVALUESFROM, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
	 */
	public void removeAllValuesFrom( Class value  ) {
		remove(ALLVALUESFROM, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, ALLVALUESFROM, value)
	 */
	public boolean hasAllValuesFrom( Class value) {
		return hasValue(ALLVALUESFROM, value);
	}

	/**
	 * @return true if the model contains a statement (this, ALLVALUESFROM, *)
	 */
	public boolean hasAllValuesFrom() {
		return hasValue(ALLVALUESFROM);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
	 */
	public void addAllValuesFrom( Class value  ) {
		add(ALLVALUESFROM, value );
	}

	/**
	 * @return all values
	 */
	public Class[] getAllAllValuesFrom() {
		return (Class[]) getAll(ALLVALUESFROM, Class.class);
	}
  

    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public int getMinCardinality() {
		return (Integer) get(MINCARDINALITY, Integer.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
	 */
	public void setMinCardinality( int value ) {
		set(MINCARDINALITY, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
	 */
	public void removeMinCardinality( int value  ) {
		remove(MINCARDINALITY, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, MINCARDINALITY, value)
	 */
	public boolean hasMinCardinality( int value) {
		return hasValue(MINCARDINALITY, value);
	}

	/**
	 * @return true if the model contains a statement (this, MINCARDINALITY, *)
	 */
	public boolean hasMinCardinality() {
		return hasValue(MINCARDINALITY);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
	 */
	public void addMinCardinality( int value  ) {
		add(MINCARDINALITY, value );
	}

	/**
	 * @return all values
	 */
	public int[] getAllMinCardinality() {
		return toIntArray((Integer[]) getAll(MINCARDINALITY, Integer.class) );
	}
  

    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Class getSomeValuesFrom() {
		return (Class) get(SOMEVALUESFROM, Class.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
	 */
	public void setSomeValuesFrom( Class value ) {
		set(SOMEVALUESFROM, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
	 */
	public void removeSomeValuesFrom( Class value  ) {
		remove(SOMEVALUESFROM, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, SOMEVALUESFROM, value)
	 */
	public boolean hasSomeValuesFrom( Class value) {
		return hasValue(SOMEVALUESFROM, value);
	}

	/**
	 * @return true if the model contains a statement (this, SOMEVALUESFROM, *)
	 */
	public boolean hasSomeValuesFrom() {
		return hasValue(SOMEVALUESFROM);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
	 */
	public void addSomeValuesFrom( Class value  ) {
		add(SOMEVALUESFROM, value );
	}

	/**
	 * @return all values
	 */
	public Class[] getAllSomeValuesFrom() {
		return (Class[]) getAll(SOMEVALUESFROM, Class.class);
	}
  

    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public int getCardinality() {
		return (Integer) get(CARDINALITY, Integer.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
	 */
	public void setCardinality( int value ) {
		set(CARDINALITY, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
	 */
	public void removeCardinality( int value  ) {
		remove(CARDINALITY, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, CARDINALITY, value)
	 */
	public boolean hasCardinality( int value) {
		return hasValue(CARDINALITY, value);
	}

	/**
	 * @return true if the model contains a statement (this, CARDINALITY, *)
	 */
	public boolean hasCardinality() {
		return hasValue(CARDINALITY);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
	 */
	public void addCardinality( int value  ) {
		add(CARDINALITY, value );
	}

	/**
	 * @return all values
	 */
	public int[] getAllCardinality() {
		return toIntArray((Integer[]) getAll(CARDINALITY, Integer.class) );
	}
  

    private static int[] toIntArray(Integer[] all) {
		// work around that java can'T auto-box arrays
		int[] result = new int[all.length];
		for (int i = 0; i < result.length; i++) {
			result[i] = all[i];
		}
		return result;
	}

	/**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Class getHasValue() {
		return (Class) get(HASVALUE, Class.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
	 */
	public void setHasValue( Class value ) {
		set(HASVALUE, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
	 */
	public void removeHasValue( Class value  ) {
		remove(HASVALUE, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, HASVALUE, value)
	 */
	public boolean hasHasValue( Class value) {
		return hasValue(HASVALUE, value);
	}

	/**
	 * @return true if the model contains a statement (this, HASVALUE, *)
	 */
	public boolean hasHasValue() {
		return hasValue(HASVALUE);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
	 */
	public void addHasValue( Class value  ) {
		add(HASVALUE, value );
	}

	/**
	 * @return all values
	 */
	public Class[] getAllHasValue() {
		return (Class[]) getAll(HASVALUE, Class.class);
	}
   
}

  
  
