
/**
 * generated by http://RDFReactor.ontoware.org on 10.05.06 00:53
 */
package org.ontoware.rdfreactor.example;

import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.Resource;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.RDFDataException;


/**
 * This class was generated by <a href="http://RDFReactor.ontoware.org">RDFReactor</a> on 10.05.06 00:53
 * This class manages access to these properties:
 * <ul>
 *   <li> Writes </li>
 * </ul>
 * Schema Comment: They are almost like normal people
 */
public class Researcher extends Person {

    /** http://purl.org/net/xamde/ns/test#Researcher */
	public static final URI RDFS_CLASS = URIImpl.createURIWithoutChecking("http://purl.org/net/xamde/ns/test#Researcher");

    /** http://purl.org/net/xamde/ns/test#writes */
	public static final URI WRITES = URIImpl.createURIWithoutChecking("http://purl.org/net/xamde/ns/test#writes");
	
	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier URI, BlankNode or URL that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	protected Researcher ( Model model, URI classURI, Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uri URI of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Researcher ( Model model, Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uri URI of this instance
	 */
	public Researcher ( Model model, URI uri ) {
		this(model, uri, true);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString A URI of this instance, represented as a String
	 * @throws ModelRuntimeException 
	 */
	public Researcher ( Model model, String uriString ) throws ModelRuntimeException {
		this(model, URIImpl.create(uriString), true);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 */
	public Researcher ( Model model, BlankNode bnode ) {
		this(model, bnode, true);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 */
	public Researcher ( Model model ) {
		this(model, RDFS_CLASS, true);
	}


    ///////////////////////////////////////////////////////////////////
    // getters, setters, ...

	/**
	 * @return all instances of this class
	 */
	public Researcher[] getAllInstances() {
		return (Researcher[]) getAllInstances(super.model, Researcher.class);
	}

	/**
	 * @return all instances of this class in the given Model
	 * @param model an RDF2Go model
	 */
	public static Researcher[] getAllInstances(Model model) {
		return (Researcher[]) getAllInstances(model, Researcher.class);
	}


    /**
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Paper getWrites() {
		return (Paper) get(WRITES, Paper.class);
	}

	/**
	 * removes all values and sets this one
	 */
	public void setWrites( Paper value ) {
		set(WRITES, value);
	}

 	/**
	 * removes a value
	 */
	public void removeWrites( Paper value  ) {
		remove(WRITES, value);
	}
  
	/**
	 * adds a value
	 */
	public void addWrites( Paper value  ) {
		add(WRITES, value );
	}
 
	/**
	 * returns all values
	 */
	public Paper[] getAllWrites() {
		return (Paper[]) getAll(WRITES, Paper.class);
	}
  }

  
  
