package org.ontoware.semversion.impl;

import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.semversion.User;

/**
 * This class was generated by <a
 * href="http://RDFReactor.ontoware.org">RDFReactor</a> on 05.10.06 00:30 This
 * class manages access to these properties:
 * <ul>
 * <li> Password </li>
 * <li> Name </li>
 * </ul>
 * Schema Comment:
 * 
 * @todo
 */
public class UserImpl implements User {

	private org.ontoware.semversion.impl.generated.User user;

	public UserImpl( org.ontoware.semversion.impl.generated.User user ) {
		this.user = user;
	}
	
	public UserImpl(Model mainModel, URI uri, String name, String pass) {
		user = new org.ontoware.semversion.impl.generated.User(mainModel, uri);
		setName(name);
		setPassword(pass);
	}
	
	/* (non-Javadoc)
	 * @see org.ontoware.semversion.impl.IUser#getUser()
	 */
	public org.ontoware.semversion.impl.generated.User getUser() {
		return this.user;
	}

	/* (non-Javadoc)
	 * @see org.ontoware.semversion.impl.IUser#getPassword()
	 */
	public java.lang.String getPassword() {
		return this.user.getPassword();
	}

	/* (non-Javadoc)
	 * @see org.ontoware.semversion.impl.IUser#setPassword(java.lang.String)
	 */
	public void setPassword(java.lang.String value) {
		this.user.setPassword(value);
	}

	/* (non-Javadoc)
	 * @see org.ontoware.semversion.impl.IUser#getName()
	 */
	public java.lang.String getName() {
		return this.user.getName();
	}

	/* (non-Javadoc)
	 * @see org.ontoware.semversion.impl.IUser#setName(java.lang.String)
	 */
	public void setName(java.lang.String value) {
		this.user.setName(value);
	}

	public URI getURI() {
		return this.user.getResource().asURI();
	}

}
