
/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 785 2007-05-31 15:47:01Z voelkel $) on 01.06.07 17:33
 */
package org.ontoware.rdfreactor.schema.rdfschema;

import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.RDFDataException;


/**
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 01.06.07 17:33
 * This class manages access to these properties:
 * <ul>
 *   <li> SubClassOf </li>
 * </ul>
 * Schema Comment: The class of classes.
 */
public class Class extends Resource {

    /** http://www.w3.org/2000/01/rdf-schema#Class */
	public static final URI RDFS_CLASS = new URIImpl("http://www.w3.org/2000/01/rdf-schema#Class", false);

    /** http://www.w3.org/2000/01/rdf-schema#subClassOf */
	public static final URI SUBCLASSOF = new URIImpl("http://www.w3.org/2000/01/rdf-schema#subClassOf",false);

    /** all property-URIs with this class as domain */
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://www.w3.org/2000/01/rdf-schema#subClassOf",false) 
    };

	
	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	protected Class ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Class ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Class ( Model model, String uriString, boolean write) {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Class ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Class ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // getters, setters, ...

	/**
	 * @param model RDF2Go model
	 * @param uri instance identifier
	 * @return an instance of Class or null if none existst
	 * @throws Exception if Model causes problems
	 */
	public static Class getInstance(Model model, URI uri) throws Exception {
		return (Class) getInstance(model, uri, Class.class);
	}

	/**
	 * @param model
	 * @param uri
	 * @return true if uri is an instance of this class in the model
	 */
	public static boolean hasInstance(Model model, URI uri) {
		return hasInstance(model, uri, RDFS_CLASS);
	}

	/**
	 * @return all instances of this class
	 */
	public Class[] getAllInstances() {
		return (Class[]) getAllInstances(super.model, Class.class);
	}

	/**
	 * @return all instances of this class in the given Model
	 * @param model an RDF2Go model
	 */
	public static Class[] getAllInstances(Model model) {
		return (Class[]) getAllInstances(model, Class.class);
	}

	/**
	 * @return all A's that have a relation 'SubClassOf' to this Class instance
	 */
	public Class[] getAllSubClassOf_Inverse() {
		return (Class[]) getAll_Inverse(Class.SUBCLASSOF, this.getResource(), Class.class);
	}

	/**
	 * add 'SubClassOf'-Inverse
	 * @param value
	 */
	public void addSubClassOf_Inverse(Class value) {
		value.add( Class.SUBCLASSOF ,this);
	}


	/**
	 * @return all A's that have a relation 'Range' to this Class instance
	 */
	public Property[] getAllRange_Inverse() {
		return (Property[]) getAll_Inverse(Property.RANGE, this.getResource(), Property.class);
	}

	/**
	 * add 'Range'-Inverse
	 * @param value
	 */
	public void addRange_Inverse(Property value) {
		value.add( Property.RANGE ,this);
	}


	/**
	 * @return all A's that have a relation 'Domain' to this Class instance
	 */
	public Property[] getAllDomain_Inverse() {
		return (Property[]) getAll_Inverse(Property.DOMAIN, this.getResource(), Property.class);
	}

	/**
	 * add 'Domain'-Inverse
	 * @param value
	 */
	public void addDomain_Inverse(Property value) {
		value.add( Property.DOMAIN ,this);
	}


	/**
	 * @return all A's that have a relation 'Type' to this Class instance
	 */
	public Resource[] getAllType_Inverse() {
		return (Resource[]) getAll_Inverse(Resource.TYPE, this.getResource(), Resource.class);
	}

	/**
	 * add 'Type'-Inverse
	 * @param value
	 */
	public void addType_Inverse(Resource value) {
		value.add( Resource.TYPE ,this);
	}



    /**
     * Schema Comment: The subject is a subclass of a class.
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Class getSubClassOf() {
		return (Class) get(SUBCLASSOF, Class.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
     * Schema Comment: The subject is a subclass of a class.
	 */
	public void setSubClassOf( Class value ) {
		set(SUBCLASSOF, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
     * Schema Comment: The subject is a subclass of a class.
	 */
	public void removeSubClassOf( Class value  ) {
		remove(SUBCLASSOF, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, SUBCLASSOF, value)
	 */
	public boolean hasSubClassOf( Class value) {
		return hasValue(SUBCLASSOF, value);
	}

	/**
	 * @return true if the model contains a statement (this, SUBCLASSOF, *)
	 */
	public boolean hasSubClassOf() {
		return hasValue(SUBCLASSOF);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
     * Schema Comment: The subject is a subclass of a class.
	 */
	public void addSubClassOf( Class value  ) {
		add(SUBCLASSOF, value );
	}

	/**
	 * @return all values
     * Schema Comment: The subject is a subclass of a class.
	 */
	public Class[] getAllSubClassOf() {
		return (Class[]) getAll(SUBCLASSOF, Class.class);
	}
   
}

  
  
