
/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 785 2007-05-31 15:47:01Z voelkel $) on 01.06.07 17:33
 */
package org.ontoware.rdfreactor.schema.rdfschema;

import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.RDFDataException;


/**
 * This class was generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 01.06.07 17:33
 * This class manages access to these properties:
 * <ul>
 *   <li> SubPropertyOf </li>
 *   <li> Range </li>
 *   <li> Domain </li>
 * </ul>
 * Schema Comment: The class of RDF properties.
 */
public class Property extends Resource {

    /** http://www.w3.org/1999/02/22-rdf-syntax-ns#Property */
	public static final URI RDFS_CLASS = new URIImpl("http://www.w3.org/1999/02/22-rdf-syntax-ns#Property", false);

    /** http://www.w3.org/2000/01/rdf-schema#subPropertyOf */
	public static final URI SUBPROPERTYOF = new URIImpl("http://www.w3.org/2000/01/rdf-schema#subPropertyOf",false);

    /** http://www.w3.org/2000/01/rdf-schema#range */
	public static final URI RANGE = new URIImpl("http://www.w3.org/2000/01/rdf-schema#range",false);

    /** http://www.w3.org/2000/01/rdf-schema#domain */
	public static final URI DOMAIN = new URIImpl("http://www.w3.org/2000/01/rdf-schema#domain",false);

    /** all property-URIs with this class as domain */
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://www.w3.org/2000/01/rdf-schema#subPropertyOf",false),
      new URIImpl("http://www.w3.org/2000/01/rdf-schema#range",false),
      new URIImpl("http://www.w3.org/2000/01/rdf-schema#domain",false) 
    };

	
	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	protected Property ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Property ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Property ( Model model, String uriString, boolean write) {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Property ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public Property ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // getters, setters, ...

	/**
	 * @param model RDF2Go model
	 * @param uri instance identifier
	 * @return an instance of Property or null if none existst
	 * @throws Exception if Model causes problems
	 */
	public static Property getInstance(Model model, URI uri) throws Exception {
		return (Property) getInstance(model, uri, Property.class);
	}

	/**
	 * @param model
	 * @param uri
	 * @return true if uri is an instance of this class in the model
	 */
	public static boolean hasInstance(Model model, URI uri) {
		return hasInstance(model, uri, RDFS_CLASS);
	}

	/**
	 * @return all instances of this class
	 */
	public Property[] getAllInstances() {
		return (Property[]) getAllInstances(super.model, Property.class);
	}

	/**
	 * @return all instances of this class in the given Model
	 * @param model an RDF2Go model
	 */
	public static Property[] getAllInstances(Model model) {
		return (Property[]) getAllInstances(model, Property.class);
	}

	/**
	 * @return all A's that have a relation 'SubPropertyOf' to this Property instance
	 */
	public Property[] getAllSubPropertyOf_Inverse() {
		return (Property[]) getAll_Inverse(Property.SUBPROPERTYOF, this.getResource(), Property.class);
	}

	/**
	 * add 'SubPropertyOf'-Inverse
	 * @param value
	 */
	public void addSubPropertyOf_Inverse(Property value) {
		value.add( Property.SUBPROPERTYOF ,this);
	}



    /**
     * Schema Comment: The subject is a subproperty of a property.
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Property getSubPropertyOf() {
		return (Property) get(SUBPROPERTYOF, Property.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
     * Schema Comment: The subject is a subproperty of a property.
	 */
	public void setSubPropertyOf( Property value ) {
		set(SUBPROPERTYOF, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
     * Schema Comment: The subject is a subproperty of a property.
	 */
	public void removeSubPropertyOf( Property value  ) {
		remove(SUBPROPERTYOF, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, SUBPROPERTYOF, value)
	 */
	public boolean hasSubPropertyOf( Property value) {
		return hasValue(SUBPROPERTYOF, value);
	}

	/**
	 * @return true if the model contains a statement (this, SUBPROPERTYOF, *)
	 */
	public boolean hasSubPropertyOf() {
		return hasValue(SUBPROPERTYOF);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
     * Schema Comment: The subject is a subproperty of a property.
	 */
	public void addSubPropertyOf( Property value  ) {
		add(SUBPROPERTYOF, value );
	}

	/**
	 * @return all values
     * Schema Comment: The subject is a subproperty of a property.
	 */
	public Property[] getAllSubPropertyOf() {
		return (Property[]) getAll(SUBPROPERTYOF, Property.class);
	}
  

    /**
     * Schema Comment: A range of the subject property.
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Class getRange() {
		return (Class) get(RANGE, Class.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
     * Schema Comment: A range of the subject property.
	 */
	public void setRange( Class value ) {
		set(RANGE, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
     * Schema Comment: A range of the subject property.
	 */
	public void removeRange( Class value  ) {
		remove(RANGE, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, RANGE, value)
	 */
	public boolean hasRange( Class value) {
		return hasValue(RANGE, value);
	}

	/**
	 * @return true if the model contains a statement (this, RANGE, *)
	 */
	public boolean hasRange() {
		return hasValue(RANGE);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
     * Schema Comment: A range of the subject property.
	 */
	public void addRange( Class value  ) {
		add(RANGE, value );
	}

	/**
	 * @return all values
     * Schema Comment: A range of the subject property.
	 */
	public Class[] getAllRange() {
		return (Class[]) getAll(RANGE, Class.class);
	}
  

    /**
     * Schema Comment: A domain of the subject property.
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Class getDomain() {
		return (Class) get(DOMAIN, Class.class);
	}

	/**
	 * removes all values and sets this one
	 * @param value the value to be set
     * Schema Comment: A domain of the subject property.
	 */
	public void setDomain( Class value ) {
		set(DOMAIN, value);
	}

 	/**
	 * removes a value
	 * @param value the value to be removed
     * Schema Comment: A domain of the subject property.
	 */
	public void removeDomain( Class value  ) {
		remove(DOMAIN, value);
	}
 
	/**
	 * @param value
	 * @return true if the model contains a statement (this, DOMAIN, value)
	 */
	public boolean hasDomain( Class value) {
		return hasValue(DOMAIN, value);
	}

	/**
	 * @return true if the model contains a statement (this, DOMAIN, *)
	 */
	public boolean hasDomain() {
		return hasValue(DOMAIN);
	}

 
	/**
	 * adds a value
	 * @param value the value to be added
     * Schema Comment: A domain of the subject property.
	 */
	public void addDomain( Class value  ) {
		add(DOMAIN, value );
	}

	/**
	 * @return all values
     * Schema Comment: A domain of the subject property.
	 */
	public Class[] getAllDomain() {
		return (Class[]) getAll(DOMAIN, Class.class);
	}
   
}

  
  
