
/**
 * generated by http://RDFReactor.ontoware.org on 08.05.06 17:17
 */
package org.ontoware.rdfreactor.schema.rdfschema;

import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.Resource;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.RDFDataException;


/**
 * This class was generated by <a href="http://RDFReactor.ontoware.org">RDFReactor</a> on 08.05.06 17:17
 * This class manages access to these properties:
 * <ul>
 *   <li> Rest </li>
 *   <li> First </li>
 * </ul>
 * Schema Comment: The class of RDF Lists.
 */
public class List extends org.ontoware.rdfreactor.schema.rdfschema.Resource {

    /** http://www.w3.org/1999/02/22-rdf-syntax-ns#List */
	public static final URI RDFS_CLASS = new URIImpl("http://www.w3.org/1999/02/22-rdf-syntax-ns#List",false);

    /** http://www.w3.org/1999/02/22-rdf-syntax-ns#rest */
	public static final URI REST = new URIImpl("http://www.w3.org/1999/02/22-rdf-syntax-ns#rest",false);

    /** http://www.w3.org/1999/02/22-rdf-syntax-ns#first */
	public static final URI FIRST = new URIImpl("http://www.w3.org/1999/02/22-rdf-syntax-ns#first",false);
	
	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier URI, BlankNode or URL that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	protected List ( Model model, URI classURI, Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uri URI of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 */
	public List ( Model model, Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uri URI of this instance
	 */
	public List ( Model model, URI uri ) {
		this(model, uri, true);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 */
	public List ( Model model, BlankNode bnode ) {
		this(model, bnode, true);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly generated URI.
	 * Creating two wrappers results in different URIs.
	 * The statement (this, rdf:type, TYPE) is written to the model
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 */
	public List ( Model model ) {
		this(model, RDFS_CLASS, true);
	}

    ///////////////////////////////////////////////////////////////////
    // getters, setters, ...

	/**
	 * @return all instances of this class
	 */
	public List[] getAllInstances() {
		return (List[]) getAllInstances(super.model, List.class);
	}

	/**
	 * @return all A's that have a relation 'Rest' to this List instance
	 */
	public List[] getAllRest_Inverse() {
		return (List[]) getAll_Inverse(List.REST, this.getResource(), List.class);
	}

	/**
	 * add 'Rest'-Inverse
	 */
	public void addRest_Inverse(List value) {
		value.add( List.REST ,this);
	}



    /**
     * Schema Comment: The rest of the subject RDF list after the first item.
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public List getRest() {
		return (List) get(REST, List.class);
	}

	/**
	 * removes all values and sets this one
     * Schema Comment: The rest of the subject RDF list after the first item.
	 */
	public void setRest( List value ) {
		set(REST, value);
	}

 	/**
	 * removes a value
     * Schema Comment: The rest of the subject RDF list after the first item.
	 */
	public void removeRest( List value  ) {
		remove(REST, value);
	}
  
	/**
	 * adds a value
     * Schema Comment: The rest of the subject RDF list after the first item.
	 */
	public void addRest( List value  ) {
		add(REST, value );
	}
 
	/**
	 * returns all values
     * Schema Comment: The rest of the subject RDF list after the first item.
	 */
	public List[] getAllRest() {
		return (List[]) getAll(REST, List.class);
	}
 

    /**
     * Schema Comment: The first item in the subject RDF list.
     * @return the only value. null if none is found
     * @throws RDFDataException, if the property has multiple values
     */
	public Resource getFirst() {
		return (Resource) get(FIRST, Resource.class);
	}

	/**
	 * removes all values and sets this one
     * Schema Comment: The first item in the subject RDF list.
	 */
	public void setFirst( Resource value ) {
		set(FIRST, value);
	}

 	/**
	 * removes a value
     * Schema Comment: The first item in the subject RDF list.
	 */
	public void removeFirst( Resource value  ) {
		remove(FIRST, value);
	}
  
	/**
	 * adds a value
     * Schema Comment: The first item in the subject RDF list.
	 */
	public void addFirst( Resource value  ) {
		add(FIRST, value );
	}
 
	/**
	 * returns all values
     * Schema Comment: The first item in the subject RDF list.
	 */
	public Resource[] getAllFirst() {
		return (Resource[]) getAll(FIRST, Resource.class);
	}
  }

  
  
